### ISSUE TITLE
How to specify ROM and RAM in a configuration file?

### ISSUE THREAD

**Issue by li-xin-yi** [MCUSec/uEmu#10]
When I tried uEmu using the unit test dataset you provide, I noticed that ROM and RAM is specified following devices that the firmware is targeted on. But I still can't figure out how to determine the correct range. 

For example, `[SAM3.cfg](https://github.com/MCUSec/uEmu-unit_tests/blob/main/SAM3X/SAM3.cfg)` is written as

``` cfg
[MEM_Config]
# Configure rom and ram used for the target firmware (at most for two of each)
rom = 0x00080000,0x40000
ram = 0x20070000,0x40000
# Configure entry address msp and vtor of target firmware (typcially only vtor need to be configured)
entry = 0x80F35
msp = 0x20088000
vtor = 0x80000
```

But when I turn to [SAM3 documentation](https://ww1.microchip.com/downloads/en/devicedoc/atmel-11057-32-bit-cortex-m3-microcontroller-sam3x-sam3a_datasheet.pdf) I can't find where the configuration data occurs after searching for it. 

Can you explain more about how to find out the configuration for different devices? Thank you very much.

**Comment by weizhou-chaojixx** [comment]
I maybe assign a larger memory region for ROM or RAM.  Ideally,  you should follow the MCU manual and actual firmware-allocated regions to specify these parameters. For example, all SAM3 unit tests only use the memory address from 0x20070000 to 0x2008000 for RAM, so the ram  parameter of mem_config could be  0x20070000, 0x10000.  Actually, you just need to make sure the ram or rom regions cover the firmware used. But larger memory regions maybe make uEmu slower.

**Comment by weizhou-chaojixx** [comment]
By. the way, since the MSP and entry address are the first and second vectors of the vector table, I have removed these two parameters, you only need to set vtor.
