### ISSUE TITLE
[Bug] qemu-system-arm segfaulting in the s2e uEmu plugin

### ISSUE THREAD

**Issue by florianhofhammer** [MCUSec/uEmu#12]
Hi,

I was testing your software and encountered a segmentation violation during the knowledge base building.
The backtrace is as follows: 
![image](https://user-images.githubusercontent.com/40687216/150138456-401c63c5-db05-4db2-ad3d-5dd3281f1731.png)

As the backtrace shows, one of the `s2e::S2EExecutionState` pointers seems to be corrupt/not pointing to a valid address and the software therefore segfaults when de-referencing the pointer.
The access happens in [this line](https://github.com/MCUSec/s2e/blob/88527c5500f68dbcb4dc8b82a812c3737aa753e7/libs2eplugins/src/s2e/Plugins/uEmu/PeripheralModelLearning.cpp#L2195) but since I'm not very familiar with the code base, I couldn't figure out where the corruption or an out-of-bounds access to the containing vector might originate from on a first glance.

Please let me know if you need further information to debug the error, e.g., the core dump.

**Comment by weizhou-chaojixx** [comment]
Hi Florian, I have run Reflow_Oven sample with current .cfg file (https://github.com/MCUSec/uEmu-real_world_firmware/blob/pre-publication/P2IM_Reflow_Oven.cfg) for KB generation phase three times. I have never seen any faults and each round can successfully generate KB file. Did you follow my instruction to run uEmu-helper script before launching uEmu script?

**Comment by florianhofhammer** [comment]
Thanks for trying to reproduce the issue!
I've run `python3 uEmu-helper.py` with the given firmware and config file from the pre-publication branch, then call `launch-uEmu.sh` (without arguments).
I reliably get the same crash over and over again but only for the `Reflow_Oven` firmware.

I'm building the system on an up-to-date Ubuntu 20.04 installation with the current `main` branch of this repository checked out, the `pre-publication` branch for the firmware repository and the rest of the required code being managed by the repo tool (referencing the current version of the `uEmu` branch for the manifest repository).

**Comment by florianhofhammer** [comment]
Commit [7b085ac8ce5a7f8a90f94ea0917bc384b35c586f](https://github.com/MCUSec/s2e/commit/7b085ac8ce5a7f8a90f94ea0917bc384b35c586f) in the S2E repository fixed it.

Thanks a lot for the quick help, @weizhou-chaojixx!
