### ISSUE TITLE
Single testcase execution

### ISSUE THREAD

**Issue by florianhofhammer** [MCUSec/uEmu#13]
Hi,

I was using the recently added functionality of executing single testcases with uEmu.
Unfortunately, some of my testcases are less than 4B long which is rejected by your code (see <https://github.com/MCUSec/s2e/blob/23efd980bebdf5aa17547b9129a0180315b67e8e/libs2eplugins/src/s2e/Plugins/Fuzzer/AFLFuzzer.cpp#L232>).

Could you briefly elaborate why this is the case? It's not quite obvious to me :)

Thank you very much for your help!

**Comment by weizhou-chaojixx** [comment]
Sorry for the delay, that is because the width of the data register is 32 bit (4B). Typically the firmware will read 4B  data at one time. I can remove such restrictions and but if your input test case is short then firmware reading requirement, uncertain high bits data may be fed.

**Comment by florianhofhammer** [comment]
Cool, thanks for your response.
