### ISSUE TITLE
Makefile missed

### ISSUE THREAD

**Issue by awnofwheat** [MCUSec/uEmu#16]
The instructions mentions this step, however, there seems no Makefile
`make -f $uEmuDIR/Makefile && make -f $uEmuDIR/Makefile install`

**Comment by weizhou-chaojixx** [comment]
Have you declared the $uEmuDIR var? Where did you put the uEmu root folder? The Makefile should exist in the root folder.

**Comment by Ownv** [comment]
The instructions mentions this step, however, there seems no Makefile
make -f $uEmuDIR/Makefile && make -f $uEmuDIR/Makefile install

**Comment by weizhou-chaojixx** [comment]
Makefile does not include in this repo. However, if you follow the instruction, you will automatically download the makefile from other repo https://github.com/MCUSec/scripts.
