### ISSUE TITLE
some problems:

### ISSUE THREAD

**Issue by Ownv** [MCUSec/uEmu#19]
some problems:
InvalidStatesDetection: Invalid States Detection is unabled in cache mode
PeripheralModelLearning: Could not open cache peripheral knowledge base file: /s2e-out-1/XML_Parser.elf-round1-state51-tbnum1063_KB.dat 
PeripheralModelLearning: Could not read peripheral regs from cache file/s2e-out-1/XML_Parser.elf-round1-state51-tbnum1063_KB.dat

**Comment by weizhou-chaojixx** [comment]
Invalid States Detection is no needed for cache mode so it has been disabled by default in cache mode. Other issues seem you have not set the correct path for the KB cache file.
