### ISSUE TITLE
The gernerated .kb file doesn't work for fuzz

### ISSUE THREAD

**Issue by kevinsungdelta** [MCUSec/uEmu#2]
I am trying to run uEmu on P2IM.Drone sample. I followed  the steps. First, I used 'launch-uEmu.sh' to generate a .kb file. Then using 'uEmu-helper.py' to consider the generated .kb file. However, it failed to execute the fuzzing. 
This is the error log:

> vagrant@ubuntu-focal:~/vagrant$ ./launch-uEmu.sh 
> Starting libs2e...
> Opening /dev/kvm
> Using module /home/vagrant/uemu/build/libs2e-release/arm-s2e-softmmu/op_helper.bc.arm
> S2E: output directory = "./s2e-out-21"
> Using log level override 'info'
> Setting console level to 'info'
> Creating plugin CorePlugin
> Creating plugin BaseInstructions
> Creating plugin Vmi
> Creating plugin RawMonitor
> Creating plugin ModuleMap
> Creating plugin ModuleExecutionDetector
> Creating plugin ARMFunctionMonitor
> Creating plugin PeripheralModelLearning
> Creating plugin InvalidStatesDetection
> Creating plugin ExternalInterrupt
> Creating plugin AFLFuzzer
> Initializing ExternalInterrupt
> Initializing InvalidStatesDetection
> InvalidStatesDetection: Invalid States Detection is unabled in cache mode
> Initializing ARMFunctionMonitor
> Initializing PeripheralModelLearning
> PeripheralModelLearning: firmware name is firmware/P2IM.Drone.elf
> PeripheralModelLearning: Could not open cache peripheral knowledge base file: s2e-last/P2IM.Drone.elf-round1-state10-tbnum1422_KB.dat
> PeripheralModelLearning: Could not read peripheral regs from cache files2e-last/P2IM.Drone.elf-round1-state10-tbnum1422_KB.dat

**Comment by weizhou-chaojixx** [comment]
According to log, it seems uEmu cannot find your generated KB file. You should make sure the path to generated KB file is correct.

**Comment by kevinsungdelta** [comment]
Thanks for the reply.  The problem is that I imported the KB file from the soft link (i.e. s2e-last). In contrast, I succeed by using the absolute directory path. Thank  you!
