### ISSUE TITLE
about warnings,What went wrong？

### ISSUE THREAD

**Issue by Ownv** [MCUSec/uEmu#21]
AFLFuzzer: 011 what happen when we are hang at pc = 0x8011cae, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x8011cbc, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x8011cf2, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x8011d02, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800e15c, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800e15e, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800e162, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800e16c, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800e176, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800e188, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800e192, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800e058, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800e10e, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800e122, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800e14e, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800e13e, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x801082a, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x801084e, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x8011d2c, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800bc66, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800bc96, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800bc9c, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800d6b8, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800d6be, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800d6ce, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800d5e8, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800d5e0, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800d6a2, maybe add it as a crash point
AFLFuzzer: 010 what happen when we are hang at pc = 0x800d50a, maybe add it as a crash point
AFLFuzzer: 010 what happen when we are hang at pc = 0x800d514, maybe add it as a crash point
AFLFuzzer: 010 what happen when we are hang at pc = 0x800d6a8, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800d6d2, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800d6c2, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800d6d6, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x8011d32, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x8011d3a, maybe add it as a crash point
AFLFuzzer: 011 what happen when we are hang at pc = 0x800e142, maybe add it as a crash point
........

**Comment by klay6** [comment]
I have also encountered this issue, but haven't found a solution yet

**Comment by weizhou-chaojixx** [comment]
This is used to record the trace before a system hangs, allowing users to determine whether it is a true hang or not.
