### ISSUE TITLE
An error occurred while running  launch-AFL.sh and launch-uEmu.sh

### ISSUE THREAD

**Issue by klay6** [MCUSec/uEmu#24]
Thank you for providing this tool！
An error occurred while running  launch-AFL.sh and launch-uEmu.sh：
I first run launch-uEmu.sh, and then it stays in this state all the time
![](https://github.com/MCUSec/uEmu/assets/109709555/1eb5f96d-aab9-4f50-a2bb-7393233e2e92)
and then I run launch-AFL.sh,but it cannot run successfully
![](https://github.com/MCUSec/uEmu/assets/109709555/82843dbc-adf1-4018-9044-ef63e09ab144)

I would like to know why this problem occurred. Thank you！

**Comment by weizhou-chaojixx** [comment]
You need to launch AFL fuzzur via `./launch-AFL.sh` at first before launching uEmu
