### ISSUE TITLE
Dead loop on KB Extraction Phase

### ISSUE THREAD

**Issue by ytlp** [MCUSec/uEmu#26]
When I used 'launch-uEmu.sh' to generate a .kb file，it ran into dead loop . How can i skip dead loop?

**Comment by ytlp** [comment]
![微信图片_20240909093820](https://github.com/user-attachments/assets/49ef03fd-ee3c-4ede-a368-c2c0ee1ca05f)

**Comment by weizhou-chaojixx** [comment]
You can add basic block address in dead loop as a kill point (like 0xa1c) (see https://github.com/MCUSec/uEmu/blob/main/docs/Configuration.md).
