### ISSUE TITLE
about qemu-system-arm error

### ISSUE THREAD

**Issue by harden614** [MCUSec/uEmu#5]
![image](https://user-images.githubusercontent.com/65664508/139437515-81c1f0f5-78b0-44bc-ad06-80cbcf492448.png)
I dont have the clock_nanosleep.c,but the qemu must use in the second phrase.
is the .c file build by cmake or make?
who can help me?

**Comment by weizhou-chaojixx** [comment]
Have you use the qemu from MCUSec repo? I never meet such problem.

**Comment by harden614** [comment]
I have already executed.Dec 24, 20217:58 PM，Willy ***@***.***> 写道：Have you use the qemu from MCUSec repo? I never meet such problem.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
