### ISSUE TITLE
abount uEmu-helper error

### ISSUE THREAD

**Issue by dokodokoR** [MCUSec/uEmu#6]
@weizhou-chaojixx 

When I ran uEmu against `heat_press`, `uEmu-helper.py` stopped running in the middle.

```bash
launch-uEmu.sh: line 83:   921 Killed  LD_PRELOAD=$LIBS2E $QEMU -k en-us $GRAPHICS -M mps2-ans2e -cpu cortex-m3 -m $QEMU_MEMORY -enable-kvm -serial file:s2e-last/serial.txt $QEMU_EXTRA_FLAGS -kernel $FIRMWARE
```
Has you or anyone seen this error before?

**Comment by guyf2010** [comment]
I have also encountered this issue, but haven't found a solution yet. Following this if anyone posts a solution.

**Comment by guyf2010** [comment]
It looks like it might be an out of memory error. I gave 32GB of RAM to the Vagrant VM, but found a single instance of uEmu using 26GB after 24 hours in the steering control binary. A larger binary could easily run the system out of resources. How much RAM did you allocate?

**Comment by dokodokoR** [comment]
@guyf2010 
I allocated 8GB/16GB. It could be due to lack of memory.

**Comment by weizhou-chaojixx** [comment]
@guyf2010 @dokodokoR 
Thanks for all your responses, I do my experiment with 32GB. I will repeat my experiments within 16GB and try to reproduce your problems and fix them.

**Comment by weizhou-chaojixx** [comment]
@guyf2010 @dokodokoR  This problem is caused by the current S2E fork mechanism, but I need some time to fundamentally replace that. A quick solution is you can use the latest configuration file in the current pre-publication branch of the real-world firmware repo.

**Comment by weizhou-chaojixx** [comment]
The original uEmu indeed consumed large memory, nearly 30G for 24h fuzzing for the worst case. I have replaced S2E fork interface with commit [a38319c](https://github.com/MCUSec/s2e/commit/a38319cf2ac40e0acc9ef65a557e8e904f9fd4df). The memory leak problem has been mitigated. Currently, the memory usage is from 1G to 20G among all real-world firmware samples after 24h fuzz testing on 8-core/16-thread Xeon server. Please sync the latest code base of uEmu and re-build before re-testing.
