### ISSUE TITLE
Can uEmu emulate stripped binaries?

### ISSUE THREAD

**Issue by AminoACID123** [MCUSec/uEmu#7]

**Comment by weizhou-chaojixx** [comment]
Based on the ARM Cortex-M architecture, the entry address of running firmware should be located in the second entry of the vector table. Thus, I have abandoned the  'entry point' option, and users only need to configure the address of the VTOR register (stored the start address of vector). Then, uEmu can automatically load the entry point from the vector table.
However, the real-world stripped binary has its specific binary format that the QEMU cannot automatically extract like .elf file. Thus, you first need to know the loading information of the binary from its header format, such as memory map and start address of vector table.
