### ISSUE TITLE
How to make uEmu run in parallel properly?

### ISSUE THREAD

**Issue by li-xin-yi** [MCUSec/uEmu#8]
First, I really appreciate your awesome paper and codes, thanks for sharing. :)

I am also trying to reproduce the results in the paper, but I found it ran more than 10x slower in knowledge extraction stage for unit tests, compared to the data in your paper, even when I have allocated 16 cores and 48 GB RAM to the vagrant instance. I noticed that the `qemu` was running with only one thread, so I doubt if the multiple cores mentioned in your paper works in accelerating the knowledge learning stage.

I tried to modify the  `S2E_MAX_PROCESSES` in [`launch-uEmu-template.sh#L28`](https://github.com/MCUSec/uEmu/blob/dbba62a03a19e3aa021742165c4bd80d8a9eefcb/launch-uEmu-template.sh#L28), which actually makes S2E run with more threads. However, after a short while, it somehow **hangs with no information and no outputs**.

Can you give me any suggestions on fixing the issue and speeding up to achieve the performance in your paper? Thank you very much.

By the way, I also want to let `uEmu` run out-of-tree, but after I modify responding paths in `uEmu-helper.py`, `launch-uEmu-template.sh` to fix the path issues when running S2E but failed. I may also need helps with figure out the files launched in each file.

**Comment by weizhou-chaojixx** [comment]
Which unit test you run is 10x slower in knowledge extraction stage compared to the data in my paper? Did you run with info level information? If you run uEmu with debug level, it will slower but it cannot be slower 10x with 16 core CPU.
